#version 450

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout (binding = 0) uniform sampler2D in_img;
layout (binding = 1, rgba8) uniform writeonly image2D out_img;

layout (constant_id = 0) const float eyeSizeRatioX = 0.;
layout (constant_id = 1) const float eyeSizeRatioY = 0.;
layout (constant_id = 2) const float centerSizeX = 0.;
layout (constant_id = 3) const float centerSizeY = 0.;
layout (constant_id = 4) const float edgeRatioX = 0.;
layout (constant_id = 5) const float edgeRatioY = 0.;

layout (push_constant) uniform FoveationCenterShifts {
    vec2 centerShiftLeft;
    vec2 centerShiftRight;
};

const vec2 eyeSizeRatio = vec2(eyeSizeRatioX, eyeSizeRatioY);
const vec2 centerSize = vec2(centerSizeX, centerSizeY);
const vec2 edgeRatio = vec2(edgeRatioX, edgeRatioY);

vec2 TextureToEyeUV(vec2 textureUV, bool isRightEye)
{
    // flip distortion horizontally for right eye
    // left: x * 2; right: (1 - x) * 2
    return vec2((textureUV.x + float(isRightEye) * (1. - 2. * textureUV.x)) * 2., textureUV.y);
}

vec2 EyeToTextureUV(vec2 eyeUV, bool isRightEye)
{
    // saturate is used to avoid color bleeding between the two sides of the texture or with the
    // black border when filtering
    // vec2 clampedUV = saturate(eyeUV);
    // left: x / 2; right 1 - (x / 2)
    // return vec2(clampedUV.x / 2. + float(isRightEye) * (1. - clampedUV.x), clampedUV.y);
    return vec2(eyeUV.x * .5 + float(isRightEye) * (1. - eyeUV.x), eyeUV.y);
}

float CompressAxis(float eyeUV, float centerSizeAxis, float centerShiftAxis, float edgeRatioAxis)
{
    float c0 = (1. - centerSizeAxis) * .5;
    float c1 = (edgeRatioAxis - 1.) * c0 * (centerShiftAxis + 1.) / edgeRatioAxis;
    float c2 = (edgeRatioAxis - 1.) * centerSizeAxis + 1.;

    float loBound = c0 * (centerShiftAxis + 1.) / c2;
    float hiBound = c0 * (centerShiftAxis - 1.) / c2 + 1.;
    float center = eyeUV * c2 / edgeRatioAxis + c1;

    if (eyeUV < loBound) {
        float d2 = eyeUV * c2;
        float g1 = eyeUV / max(loBound, 1e-6);
        return g1 * center + (1. - g1) * d2;
    }

    if (eyeUV > hiBound) {
        float d3 = (eyeUV - 1.) * c2 + 1.;
        float g2 = (1. - eyeUV) / max(1. - hiBound, 1e-6);
        return g2 * center + (1. - g2) * d3;
    }

    return center;
}

void main()
{
    ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
    vec2 uv = (vec2(pos) + 0.5f) / imageSize(out_img);

    bool isRightEye = uv.x > 0.5;
    vec2 eyeUV = TextureToEyeUV(uv, isRightEye) / eyeSizeRatio;
    vec2 centerShift = isRightEye ? centerShiftRight : centerShiftLeft;

    vec2 compressedUV = vec2(
        CompressAxis(eyeUV.x, centerSize.x, centerShift.x, edgeRatio.x),
        CompressAxis(eyeUV.y, centerSize.y, centerShift.y, edgeRatio.y)
    );

    imageStore(out_img, pos, texture(in_img, EyeToTextureUV(compressedUV, isRightEye)));
}
